Repository nerfstudio-project/nerfstudio, pull requests merged in 2023-05, with the labels that each got.

#1928 Add hints to viewer
  nerfstudio/viewer/server/control_panel.py
  nerfstudio/viewer/server/viewer_elements.py
  nerfstudio/viewer/viser/message_api.py
Labels: quality of life, python

#1926 Update contributing docs
  README.md
  docs/index.md
  docs/reference/contributing.md
Labels: documentation

#1929 Create PCA colormap for images with channels > 3
  nerfstudio/utils/colormaps.py
  nerfstudio/viewer/server/control_panel.py
Labels: quality of life, python

#1934 Discover external methods from CLI
  docs/nerfology/methods/index.md
  nerfstudio/configs/external_methods.py
  nerfstudio/configs/method_configs.py
Labels: enhancement, quality of life

#1922 Switching to Torch 2.0 by default.
  Dockerfile
  README.md
  docs/quickstart/installation.md
  nerfstudio/cameras/camera_utils.py
  nerfstudio/engine/schedulers.py
  nerfstudio/model_components/scene_colliders.py
  nerfstudio/utils/math.py
  nerfstudio/utils/misc.py
  nerfstudio/utils/tensor_dataclass.py
  pyproject.toml
Labels: enhancement, speedup, dependencies, python

#1940 Fix some typing problems
  nerfstudio/cameras/rays.py
  nerfstudio/engine/callbacks.py
  nerfstudio/engine/schedulers.py
  nerfstudio/engine/trainer.py
  nerfstudio/exporter/marching_cubes.py
  nerfstudio/field_components/activations.py
  nerfstudio/field_components/encodings.py
  nerfstudio/field_components/temporal_grid.py
  nerfstudio/fields/base_field.py
  nerfstudio/fields/density_fields.py
  nerfstudio/fields/nerfacto_field.py
  nerfstudio/fields/nerfplayer_nerfacto_field.py
  nerfstudio/fields/nerfplayer_ngp_field.py
  nerfstudio/fields/sdf_field.py
  nerfstudio/generative/stable_diffusion.py
  nerfstudio/model_components/losses.py
  nerfstudio/model_components/ray_generators.py
  nerfstudio/model_components/ray_samplers.py
  nerfstudio/models/base_surface_model.py
  nerfstudio/models/depth_nerfacto.py
  nerfstudio/models/mipnerf.py
  nerfstudio/models/nerfplayer_nerfacto.py
  nerfstudio/models/tensorf.py
  nerfstudio/pipelines/base_pipeline.py
  nerfstudio/utils/misc.py
  nerfstudio/utils/plotly_utils.py
  nerfstudio/utils/tensor_dataclass.py
Labels: quality of life, python

#1949 Add pre-commit
  .pre-commit-config.yaml
  docs/reference/contributing.md
  pyproject.toml
Labels: quality of life, python

#1896 output jpg option and progress bar
  nerfstudio/scripts/render.py
Labels: enhancement, quality of life, python

#1804 Expose viewer controls to pipeline
  docs/developer_guides/viewer/index.md
  docs/developer_guides/viewer/viewer_control.md
  nerfstudio/scripts/viewer/sync_viser_message_defs.py
  nerfstudio/viewer/app/package.json
  nerfstudio/viewer/app/src/App.jsx
  nerfstudio/viewer/app/src/index.jsx
  nerfstudio/viewer/app/src/index.scss
  nerfstudio/viewer/app/src/modules/ConfigPanel/ConfigPanel.jsx
  nerfstudio/viewer/app/src/modules/Scene/Scene.jsx
  nerfstudio/viewer/app/src/modules/Scene/drawing.js
  nerfstudio/viewer/app/src/modules/SidePanel/ScenePanel/ScenePanel.jsx
  nerfstudio/viewer/app/src/modules/SidePanel/SidePanel.jsx
  nerfstudio/viewer/app/src/modules/ViewerWindow/ViewerWindow.jsx
  nerfstudio/viewer/app/src/modules/WebSocket/ViserMessages.tsx
  nerfstudio/viewer/app/src/modules/WebSocket/ViserWebSocket.tsx
  nerfstudio/viewer/app/yarn.lock
  nerfstudio/viewer/server/render_state_machine.py
  nerfstudio/viewer/server/viewer_elements.py
  nerfstudio/viewer/server/viewer_state.py
  nerfstudio/viewer/viser/message_api.py
  nerfstudio/viewer/viser/messages.py
Labels: viewer, javascript

#1962 Backward compatibility for torch 1.x and fix for windows
  nerfstudio/cameras/camera_utils.py
  nerfstudio/engine/schedulers.py
  nerfstudio/model_components/scene_colliders.py
  nerfstudio/utils/math.py
  nerfstudio/utils/misc.py
  pyproject.toml
Labels: dependencies, windows, python

#1959 generalize mask collation to other image-like data
  nerfstudio/data/datamanagers/base_datamanager.py
Labels: python

#1973 Basic viser frontend
  nerfstudio/configs/experiment_config.py
  nerfstudio/engine/trainer.py
  nerfstudio/utils/decorators.py
  nerfstudio/viewer_beta/__init__.py
  nerfstudio/viewer_beta/render_state_machine.py
  nerfstudio/viewer_beta/utils.py
  nerfstudio/viewer_beta/viewer_state.py
  pyproject.toml
Labels: viewer

#1932 Added at_train_end logic to base pipeline
  nerfstudio/engine/callbacks.py
  nerfstudio/engine/trainer.py
Labels: enhancement, quality of life, python

#1994 style(ruff): provide better integration with ruff vscode extension
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: quality of life

#1936 Ability to use vanilla pytorch instead of tcnn for Nerfacto
  nerfstudio/configs/base_config.py
  nerfstudio/engine/trainer.py
  nerfstudio/field_components/encodings.py
  nerfstudio/field_components/mlp.py
  nerfstudio/fields/density_fields.py
  nerfstudio/fields/instant_ngp_field.py
  nerfstudio/fields/nerfacto_field.py
  nerfstudio/model_components/losses.py
  nerfstudio/model_components/ray_samplers.py
  nerfstudio/models/base_model.py
  nerfstudio/models/base_surface_model.py
  nerfstudio/models/instant_ngp.py
  nerfstudio/models/nerfacto.py
  nerfstudio/models/neus_facto.py
  nerfstudio/models/semantic_nerfw.py
  nerfstudio/scripts/train.py
  nerfstudio/utils/printing.py
  tests/field_components/test_encodings.py
  tests/test_train.py
Labels: enhancement, python
