Repository nerfstudio-project/nerfstudio, pull requests merged in 2023-02, with the labels that each got.

#1347 double-quote filenames in process-data commands so that on Windows, paths with spaces don't fail
  nerfstudio/process_data/process_data_utils.py
  scripts/process_data.py
Labels: help wanted

#1501 Fixes bug introduced in #1499 preventing load_from_checkpoint to work correctly
  nerfstudio/pipelines/base_pipeline.py
  tests/pipelines/test_vanilla_pipeline.py
Labels: bug

#1515 feat: improve type hints
  nerfstudio/cameras/camera_utils.py
  nerfstudio/cameras/cameras.py
  nerfstudio/cameras/rays.py
  nerfstudio/exporter/texture_utils.py
  nerfstudio/exporter/tsdf_utils.py
  nerfstudio/plugins/registry.py
Labels: quality of life

#1524 feat(fields): Improve Type Hints
  nerfstudio/fields/base_field.py
  nerfstudio/fields/density_fields.py
  nerfstudio/fields/instant_ngp_field.py
  nerfstudio/fields/nerfacto_field.py
  nerfstudio/fields/nerfplayer_nerfacto_field.py
  nerfstudio/fields/nerfplayer_ngp_field.py
  nerfstudio/fields/nerfw_field.py
  nerfstudio/fields/semantic_nerf_field.py
  nerfstudio/fields/tensorf_field.py
  nerfstudio/fields/vanilla_nerf_field.py
Labels: quality of life
